// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

private func doubleEqualsRlnApi(_ lhs: Double, _ rhs: Double) -> Bool {
  return (lhs.isNaN && rhs.isNaN) || lhs == rhs
}

private func doubleHashRlnApi(_ value: Double, _ hasher: inout Hasher) {
  if value.isNaN {
    hasher.combine(0x7FF8000000000000)
  } else {
    // Normalize -0.0 to 0.0
    hasher.combine(value == 0 ? 0 : value)
  }
}

func deepEqualsRlnApi(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
    return true

  case is (Void, Void):
    return true

  case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !deepEqualsRlnApi(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsArray, let rhsArray) as ([Double], [Double]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !doubleEqualsRlnApi(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard lhsDictionary.count == rhsDictionary.count else { return false }
    for (lhsKey, lhsValue) in lhsDictionary {
      var found = false
      for (rhsKey, rhsValue) in rhsDictionary {
        if deepEqualsRlnApi(lhsKey, rhsKey) {
          if deepEqualsRlnApi(lhsValue, rhsValue) {
            found = true
            break
          } else {
            return false
          }
        }
      }
      if !found { return false }
    }
    return true

  case (let lhs as Double, let rhs as Double):
    return doubleEqualsRlnApi(lhs, rhs)

  case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
    return lhsHashable == rhsHashable

  default:
    return false
  }
}

func deepHashRlnApi(value: Any?, hasher: inout Hasher) {
  let cleanValue = nilOrValue(value) as Any?
  if let cleanValue = cleanValue {
    if let doubleValue = cleanValue as? Double {
      doubleHashRlnApi(doubleValue, &hasher)
    } else if let valueList = cleanValue as? [Any?] {
      for item in valueList {
        deepHashRlnApi(value: item, hasher: &hasher)
      }
    } else if let valueList = cleanValue as? [Double] {
      for item in valueList {
        doubleHashRlnApi(item, &hasher)
      }
    } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
      var result = 0
      for (key, value) in valueDict {
        var entryKeyHasher = Hasher()
        deepHashRlnApi(value: key, hasher: &entryKeyHasher)
        var entryValueHasher = Hasher()
        deepHashRlnApi(value: value, hasher: &entryValueHasher)
        result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
      }
      hasher.combine(result)
    } else if let hashableValue = cleanValue as? AnyHashable {
      hasher.combine(hashableValue)
    } else {
      hasher.combine(String(describing: cleanValue))
    }
  } else {
    hasher.combine(0)
  }
}


/// Generated class from Pigeon that represents data sent in messages.
struct RlnNativeArtifactInfo: Hashable {
  var platform: String
  var rlnVersion: String
  var reactNativeParityVersion: String
  var bridge: String
  var nativeArtifact: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> RlnNativeArtifactInfo? {
    let platform = pigeonVar_list[0] as! String
    let rlnVersion = pigeonVar_list[1] as! String
    let reactNativeParityVersion = pigeonVar_list[2] as! String
    let bridge = pigeonVar_list[3] as! String
    let nativeArtifact = pigeonVar_list[4] as! String

    return RlnNativeArtifactInfo(
      platform: platform,
      rlnVersion: rlnVersion,
      reactNativeParityVersion: reactNativeParityVersion,
      bridge: bridge,
      nativeArtifact: nativeArtifact
    )
  }
  func toList() -> [Any?] {
    return [
      platform,
      rlnVersion,
      reactNativeParityVersion,
      bridge,
      nativeArtifact,
    ]
  }
  static func == (lhs: RlnNativeArtifactInfo, rhs: RlnNativeArtifactInfo) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsRlnApi(lhs.platform, rhs.platform) && deepEqualsRlnApi(lhs.rlnVersion, rhs.rlnVersion) && deepEqualsRlnApi(lhs.reactNativeParityVersion, rhs.reactNativeParityVersion) && deepEqualsRlnApi(lhs.bridge, rhs.bridge) && deepEqualsRlnApi(lhs.nativeArtifact, rhs.nativeArtifact)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("RlnNativeArtifactInfo")
    deepHashRlnApi(value: platform, hasher: &hasher)
    deepHashRlnApi(value: rlnVersion, hasher: &hasher)
    deepHashRlnApi(value: reactNativeParityVersion, hasher: &hasher)
    deepHashRlnApi(value: bridge, hasher: &hasher)
    deepHashRlnApi(value: nativeArtifact, hasher: &hasher)
  }
}

private class RlnApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return RlnNativeArtifactInfo.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class RlnApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? RlnNativeArtifactInfo {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class RlnApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return RlnApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return RlnApiPigeonCodecWriter(data: data)
  }
}

class RlnApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = RlnApiPigeonCodec(readerWriter: RlnApiPigeonCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol RlnHostApi {
  func getNativeArtifactInfo() throws -> RlnNativeArtifactInfo
  func rlnCreateNode(storageDirPath: String, daemonListeningPort: Int64, ldkPeerListeningPort: Int64, network: String, maxMediaUploadSizeMb: Int64, enableVirtualChannelsV0: Bool?, virtualPeerPubkeys: [String]?, vssUrl: String?, vssAllowHttp: Bool, vssAllowEmptyRestore: Bool, lspBaseUrl: String?, lspBearerToken: String?) throws -> Int64
  func rlnInitNode(nodeId: Int64, password: String, mnemonic: String?) throws -> String
  func rlnCreateNativeExternalSigner(seedHex: String, network: String, permissivePolicy: Bool) throws -> Int64
  func rlnInitNodeWithNativeExternalSigner(nodeId: Int64, signerId: Int64) throws
  func rlnAttachNativeExternalSigner(nodeId: Int64, signerId: Int64) throws
  func rlnUnlockNodeWithNativeExternalSigner(nodeId: Int64, signerId: Int64, bitcoindRpcUsername: String?, bitcoindRpcPassword: String?, bitcoindRpcHost: String?, bitcoindRpcPort: Int64?, indexerUrl: String?, proxyEndpoint: String?, announceAddresses: [String], announceAlias: String?, gossipRgsServerUrl: String?) throws
  func rlnDestroyNativeExternalSigner(signerId: Int64) throws
  func rlnInitNodeWithExternalSigner(nodeId: Int64, nodePublicKeyHex: String, accountXpubVanilla: String, accountXpubColored: String, masterFingerprint: String, protocolVersion: String, apiLevel: Int64) throws
  func rlnUnlockNode(nodeId: Int64, password: String, bitcoindRpcUsername: String?, bitcoindRpcPassword: String?, bitcoindRpcHost: String?, bitcoindRpcPort: Int64?, indexerUrl: String?, proxyEndpoint: String?, announceAddresses: [String], announceAlias: String?, gossipRgsServerUrl: String?) throws
  func rlnDestroyNode(nodeId: Int64) throws
  func rlnNodeInfo(nodeId: Int64) throws -> [AnyHashable?: Any?]
  func rlnNetworkInfo(nodeId: Int64) throws -> [AnyHashable?: Any?]
  func rlnListPeers(nodeId: Int64) throws -> [[AnyHashable?: Any?]]
  func rlnConnectPeer(nodeId: Int64, peerPubkeyAndAddr: String) throws
  func rlnDisconnectPeer(nodeId: Int64, peerPubkey: String) throws
  func rlnListChannels(nodeId: Int64) throws -> [[AnyHashable?: Any?]]
  func rlnOpenChannel(nodeId: Int64, peerPubkeyAndOptAddr: String, capacitySat: Int64, pushMsat: Int64, publicChannel: Bool, withAnchors: Bool, feeBaseMsat: Int64?, feeProportionalMillionths: Int64?, temporaryChannelId: String?, assetId: String?, assetAmount: Int64?, pushAssetAmount: Int64?, virtualOpenMode: String?) throws -> [AnyHashable?: Any?]
  func rlnCloseChannel(nodeId: Int64, channelId: String, peerPubkey: String, force: Bool) throws
  func rlnListPayments(nodeId: Int64) throws -> [[AnyHashable?: Any?]]
  func rlnAddress(nodeId: Int64) throws -> [AnyHashable?: Any?]
  func rlnAssetBalance(nodeId: Int64, assetId: String) throws -> [AnyHashable?: Any?]
  func rlnBackup(nodeId: Int64, backupPath: String, password: String) throws
  func rlnBtcBalance(nodeId: Int64, skipSync: Bool) throws -> [AnyHashable?: Any?]
  func rlnCheckIndexerUrl(nodeId: Int64, indexerUrl: String) throws -> [AnyHashable?: Any?]
  func rlnCheckProxyEndpoint(nodeId: Int64, proxyEndpoint: String) throws
  func rlnCreateUtxos(nodeId: Int64, upTo: Bool, num: Int64?, size: Int64?, feeRate: Double, skipSync: Bool) throws
  func rlnDecodeLnInvoice(nodeId: Int64, invoice: String) throws -> [AnyHashable?: Any?]
  func rlnDecodeRgbInvoice(nodeId: Int64, invoice: String) throws -> [AnyHashable?: Any?]
  func rlnEstimateFee(nodeId: Int64, blocks: Int64) throws -> [AnyHashable?: Any?]
  func rlnFailTransfers(nodeId: Int64, batchTransferIdx: Int64?, noAssetOnly: Bool, skipSync: Bool) throws -> [AnyHashable?: Any?]
  func rlnGetChannelId(nodeId: Int64, temporaryChannelId: String) throws -> String
  func rlnGetPayment(nodeId: Int64, paymentHash: String) throws -> [AnyHashable?: Any?]
  func rlnInvoiceStatus(nodeId: Int64, invoice: String) throws -> [AnyHashable?: Any?]
  func rlnKeysend(nodeId: Int64, destPubkey: String, amtMsat: Int64, assetId: String?, assetAmount: Int64?) throws -> [AnyHashable?: Any?]
  func rlnListAssets(nodeId: Int64, filterAssetSchemas: [String]) throws -> [AnyHashable?: Any?]
  func rlnListTransactions(nodeId: Int64, skipSync: Bool) throws -> [[AnyHashable?: Any?]]
  func rlnListTransfers(nodeId: Int64, assetId: String) throws -> [[AnyHashable?: Any?]]
  func rlnListUnspents(nodeId: Int64, skipSync: Bool) throws -> [[AnyHashable?: Any?]]
  func rlnLnInvoice(nodeId: Int64, amtMsat: Int64?, expirySec: Int64, assetId: String?, assetAmount: Int64?, paymentHash: String?, minFinalCltvExpiryDelta: Int64?) throws -> [AnyHashable?: Any?]
  func rlnClaimHodlInvoice(nodeId: Int64, paymentHash: String, paymentPreimage: String) throws -> [AnyHashable?: Any?]
  func rlnCancelHodlInvoice(nodeId: Int64, paymentHash: String) throws
  func rlnApayNew(nodeId: Int64, hostNodeId: String) throws -> [AnyHashable?: Any?]
  func rlnApayNewWithAddress(nodeId: Int64, hostNodeId: String, username: String, domain: String) throws -> [AnyHashable?: Any?]
  func rlnRefreshTransfers(nodeId: Int64, skipSync: Bool) throws
  func rlnRgbInvoice(nodeId: Int64, assetId: String?, assignmentAmount: Int64?, durationSeconds: Int64?, minConfirmations: Int64, witness: Bool) throws -> [AnyHashable?: Any?]
  func rlnSendBtc(nodeId: Int64, amount: Int64, address: String, feeRate: Double, skipSync: Bool) throws -> [AnyHashable?: Any?]
  func rlnSendPayment(nodeId: Int64, invoice: String, amtMsat: Int64?, assetId: String?, assetAmount: Int64?) throws -> [AnyHashable?: Any?]
  func rlnSendRgb(nodeId: Int64, donation: Bool, feeRate: Double, minConfirmations: Int64, skipSync: Bool, assetId: String, recipientId: String, amount: Int64, transportEndpoints: [String], witnessAmountSat: Int64?, witnessBlinding: Int64?) throws -> [AnyHashable?: Any?]
  func rlnShutdown(nodeId: Int64) throws
  func rlnSync(nodeId: Int64) throws
  func rlnIssueAssetNia(nodeId: Int64, ticker: String, name: String, precision: Int64, amounts: [Int64]) throws -> Any?
  func rlnIssueAssetCfa(nodeId: Int64, name: String, details: String?, precision: Int64, amounts: [Int64], fileDigest: String?) throws -> Any?
  func rlnIssueAssetIfa(nodeId: Int64, ticker: String, name: String, precision: Int64, amounts: [Int64], inflationAmounts: [Int64], rejectListUrl: String?) throws -> Any?
  func rlnIssueAssetUda(nodeId: Int64, ticker: String, name: String, details: String?, precision: Int64, mediaFileDigest: String?, attachmentsFileDigests: [String]) throws -> Any?
  func rlnVssClearFence(nodeId: Int64, password: String) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class RlnHostApiSetup {
  static var codec: FlutterStandardMessageCodec { RlnApiPigeonCodec.shared }
  /// Sets up an instance of `RlnHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: RlnHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let getNativeArtifactInfoChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rgb_sdk_flutter.RlnHostApi.getNativeArtifactInfo\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getNativeArtifactInfoChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getNativeArtifactInfo()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getNativeArtifactInfoChannel.setMessageHandler(nil)
    }
    let rlnCreateNodeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rgb_sdk_flutter.RlnHostApi.rlnCreateNode\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      rlnCreateNodeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let storageDirPathArg = args[0] as! String
        let daemonListeningPortArg = args[1] as! Int64
        let ldkPeerListeningPortArg = args[2] as! Int64
        let networkArg = args[3] as! String
        let maxMediaUploadSizeMbArg = args[4] as! Int64
        let enableVirtualChannelsV0Arg: Bool? = nilOrValue(args[5])
        let virtualPeerPubkeysArg: [String]? = nilOrValue(args[6])
        let vssUrlArg: String? = nilOrValue(args[7])
        let vssAllowHttpArg = args[8] as! Bool
        let vssAllowEmptyRestoreArg = args[9] as! Bool
        let lspBaseUrlArg: String? = nilOrValue(args[10])
        let lspBearerTokenArg: String? = nilOrValue(args[11])
        do {
          let result = try api.rlnCreateNode(storageDirPath: storageDirPathArg, daemonListeningPort: daemonListeningPortArg, ldkPeerListeningPort: ldkPeerListeningPortArg, network: networkArg, maxMediaUploadSizeMb: maxMediaUploadSizeMbArg, enableVirtualChannelsV0: enableVirtualChannelsV0Arg, virtualPeerPubkeys: virtualPeerPubkeysArg, vssUrl: vssUrlArg, vssAllowHttp: vssAllowHttpArg, vssAllowEmptyRestore: vssAllowEmptyRestoreArg, lspBaseUrl: lspBaseUrlArg, lspBearerToken: lspBearerTokenArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      rlnCreateNodeChannel.setMessageHandler(nil)
    }
    let rlnInitNodeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rgb_sdk_flutter.RlnHostApi.rlnInitNode\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      rlnInitNodeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let nodeIdArg = args[0] as! Int64
        let passwordArg = args[1] as! String
        let mnemonicArg: String? = nilOrValue(args[2])
        do {
          let result = try api.rlnInitNode(nodeId: nodeIdArg, password: passwordArg, mnemonic: mnemonicArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      rlnInitNodeChannel.setMessageHandler(nil)
    }
    let rlnCreateNativeExternalSignerChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rgb_sdk_flutter.RlnHostApi.rlnCreateNativeExternalSigner\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      rlnCreateNativeExternalSignerChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let seedHexArg = args[0] as! String
        let networkArg = args[1] as! String
        let permissivePolicyArg = args[2] as! Bool
        do {
          let result = try api.rlnCreateNativeExternalSigner(seedHex: seedHexArg, network: networkArg, permissivePolicy: permissivePolicyArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      rlnCreateNativeExternalSignerChannel.setMessageHandler(nil)
    }
    let rlnInitNodeWithNativeExternalSignerChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rgb_sdk_flutter.RlnHostApi.rlnInitNodeWithNativeExternalSigner\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      rlnInitNodeWithNativeExternalSignerChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let nodeIdArg = args[0] as! Int64
        let signerIdArg = args[1] as! Int64
        do {
          try api.rlnInitNodeWithNativeExternalSigner(nodeId: nodeIdArg, signerId: signerIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      rlnInitNodeWithNativeExternalSignerChannel.setMessageHandler(nil)
    }
    let rlnAttachNativeExternalSignerChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rgb_sdk_flutter.RlnHostApi.rlnAttachNativeExternalSigner\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      rlnAttachNativeExternalSignerChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let nodeIdArg = args[0] as! Int64
        let signerIdArg = args[1] as! Int64
        do {
          try api.rlnAttachNativeExternalSigner(nodeId: nodeIdArg, signerId: signerIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      rlnAttachNativeExternalSignerChannel.setMessageHandler(nil)
    }
    let rlnUnlockNodeWithNativeExternalSignerChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rgb_sdk_flutter.RlnHostApi.rlnUnlockNodeWithNativeExternalSigner\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      rlnUnlockNodeWithNativeExternalSignerChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let nodeIdArg = args[0] as! Int64
        let signerIdArg = args[1] as! Int64
        let bitcoindRpcUsernameArg: String? = nilOrValue(args[2])
        let bitcoindRpcPasswordArg: String? = nilOrValue(args[3])
        let bitcoindRpcHostArg: String? = nilOrValue(args[4])
        let bitcoindRpcPortArg: Int64? = nilOrValue(args[5])
        let indexerUrlArg: String? = nilOrValue(args[6])
        let proxyEndpointArg: String? = nilOrValue(args[7])
        let announceAddressesArg = args[8] as! [String]
        let announceAliasArg: String? = nilOrValue(args[9])
        let gossipRgsServerUrlArg: String? = nilOrValue(args[10])
        do {
          try api.rlnUnlockNodeWithNativeExternalSigner(nodeId: nodeIdArg, signerId: signerIdArg, bitcoindRpcUsername: bitcoindRpcUsernameArg, bitcoindRpcPassword: bitcoindRpcPasswordArg, bitcoindRpcHost: bitcoindRpcHostArg, bitcoindRpcPort: bitcoindRpcPortArg, indexerUrl: indexerUrlArg, proxyEndpoint: proxyEndpointArg, announceAddresses: announceAddressesArg, announceAlias: announceAliasArg, gossipRgsServerUrl: gossipRgsServerUrlArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      rlnUnlockNodeWithNativeExternalSignerChannel.setMessageHandler(nil)
    }
    let rlnDestroyNativeExternalSignerChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rgb_sdk_flutter.RlnHostApi.rlnDestroyNativeExternalSigner\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      rlnDestroyNativeExternalSignerChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let signerIdArg = args[0] as! Int64
        do {
          try api.rlnDestroyNativeExternalSigner(signerId: signerIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      rlnDestroyNativeExternalSignerChannel.setMessageHandler(nil)
    }
    let rlnInitNodeWithExternalSignerChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rgb_sdk_flutter.RlnHostApi.rlnInitNodeWithExternalSigner\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      rlnInitNodeWithExternalSignerChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let nodeIdArg = args[0] as! Int64
        let nodePublicKeyHexArg = args[1] as! String
        let accountXpubVanillaArg = args[2] as! String
        let accountXpubColoredArg = args[3] as! String
        let masterFingerprintArg = args[4] as! String
        let protocolVersionArg = args[5] as! String
        let apiLevelArg = args[6] as! Int64
        do {
          try api.rlnInitNodeWithExternalSigner(nodeId: nodeIdArg, nodePublicKeyHex: nodePublicKeyHexArg, accountXpubVanilla: accountXpubVanillaArg, accountXpubColored: accountXpubColoredArg, masterFingerprint: masterFingerprintArg, protocolVersion: protocolVersionArg, apiLevel: apiLevelArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      rlnInitNodeWithExternalSignerChannel.setMessageHandler(nil)
    }
    let rlnUnlockNodeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rgb_sdk_flutter.RlnHostApi.rlnUnlockNode\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      rlnUnlockNodeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let nodeIdArg = args[0] as! Int64
        let passwordArg = args[1] as! String
        let bitcoindRpcUsernameArg: String? = nilOrValue(args[2])
        let bitcoindRpcPasswordArg: String? = nilOrValue(args[3])
        let bitcoindRpcHostArg: String? = nilOrValue(args[4])
        let bitcoindRpcPortArg: Int64? = nilOrValue(args[5])
        let indexerUrlArg: String? = nilOrValue(args[6])
        let proxyEndpointArg: String? = nilOrValue(args[7])
        let announceAddressesArg = args[8] as! [String]
        let announceAliasArg: String? = nilOrValue(args[9])
        let gossipRgsServerUrlArg: String? = nilOrValue(args[10])
        do {
          try api.rlnUnlockNode(nodeId: nodeIdArg, password: passwordArg, bitcoindRpcUsername: bitcoindRpcUsernameArg, bitcoindRpcPassword: bitcoindRpcPasswordArg, bitcoindRpcHost: bitcoindRpcHostArg, bitcoindRpcPort: bitcoindRpcPortArg, indexerUrl: indexerUrlArg, proxyEndpoint: proxyEndpointArg, announceAddresses: announceAddressesArg, announceAlias: announceAliasArg, gossipRgsServerUrl: gossipRgsServerUrlArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      rlnUnlockNodeChannel.setMessageHandler(nil)
    }
    let rlnDestroyNodeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rgb_sdk_flutter.RlnHostApi.rlnDestroyNode\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      rlnDestroyNodeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let nodeIdArg = args[0] as! Int64
        do {
          try api.rlnDestroyNode(nodeId: nodeIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      rlnDestroyNodeChannel.setMessageHandler(nil)
    }
    let rlnNodeInfoChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rgb_sdk_flutter.RlnHostApi.rlnNodeInfo\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      rlnNodeInfoChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let nodeIdArg = args[0] as! Int64
        do {
          let result = try api.rlnNodeInfo(nodeId: nodeIdArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      rlnNodeInfoChannel.setMessageHandler(nil)
    }
    let rlnNetworkInfoChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rgb_sdk_flutter.RlnHostApi.rlnNetworkInfo\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      rlnNetworkInfoChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let nodeIdArg = args[0] as! Int64
        do {
          let result = try api.rlnNetworkInfo(nodeId: nodeIdArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      rlnNetworkInfoChannel.setMessageHandler(nil)
    }
    let rlnListPeersChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rgb_sdk_flutter.RlnHostApi.rlnListPeers\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      rlnListPeersChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let nodeIdArg = args[0] as! Int64
        do {
          let result = try api.rlnListPeers(nodeId: nodeIdArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      rlnListPeersChannel.setMessageHandler(nil)
    }
    let rlnConnectPeerChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rgb_sdk_flutter.RlnHostApi.rlnConnectPeer\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      rlnConnectPeerChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let nodeIdArg = args[0] as! Int64
        let peerPubkeyAndAddrArg = args[1] as! String
        do {
          try api.rlnConnectPeer(nodeId: nodeIdArg, peerPubkeyAndAddr: peerPubkeyAndAddrArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      rlnConnectPeerChannel.setMessageHandler(nil)
    }
    let rlnDisconnectPeerChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rgb_sdk_flutter.RlnHostApi.rlnDisconnectPeer\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      rlnDisconnectPeerChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let nodeIdArg = args[0] as! Int64
        let peerPubkeyArg = args[1] as! String
        do {
          try api.rlnDisconnectPeer(nodeId: nodeIdArg, peerPubkey: peerPubkeyArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      rlnDisconnectPeerChannel.setMessageHandler(nil)
    }
    let rlnListChannelsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rgb_sdk_flutter.RlnHostApi.rlnListChannels\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      rlnListChannelsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let nodeIdArg = args[0] as! Int64
        do {
          let result = try api.rlnListChannels(nodeId: nodeIdArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      rlnListChannelsChannel.setMessageHandler(nil)
    }
    let rlnOpenChannelChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rgb_sdk_flutter.RlnHostApi.rlnOpenChannel\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      rlnOpenChannelChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let nodeIdArg = args[0] as! Int64
        let peerPubkeyAndOptAddrArg = args[1] as! String
        let capacitySatArg = args[2] as! Int64
        let pushMsatArg = args[3] as! Int64
        let publicChannelArg = args[4] as! Bool
        let withAnchorsArg = args[5] as! Bool
        let feeBaseMsatArg: Int64? = nilOrValue(args[6])
        let feeProportionalMillionthsArg: Int64? = nilOrValue(args[7])
        let temporaryChannelIdArg: String? = nilOrValue(args[8])
        let assetIdArg: String? = nilOrValue(args[9])
        let assetAmountArg: Int64? = nilOrValue(args[10])
        let pushAssetAmountArg: Int64? = nilOrValue(args[11])
        let virtualOpenModeArg: String? = nilOrValue(args[12])
        do {
          let result = try api.rlnOpenChannel(nodeId: nodeIdArg, peerPubkeyAndOptAddr: peerPubkeyAndOptAddrArg, capacitySat: capacitySatArg, pushMsat: pushMsatArg, publicChannel: publicChannelArg, withAnchors: withAnchorsArg, feeBaseMsat: feeBaseMsatArg, feeProportionalMillionths: feeProportionalMillionthsArg, temporaryChannelId: temporaryChannelIdArg, assetId: assetIdArg, assetAmount: assetAmountArg, pushAssetAmount: pushAssetAmountArg, virtualOpenMode: virtualOpenModeArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      rlnOpenChannelChannel.setMessageHandler(nil)
    }
    let rlnCloseChannelChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rgb_sdk_flutter.RlnHostApi.rlnCloseChannel\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      rlnCloseChannelChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let nodeIdArg = args[0] as! Int64
        let channelIdArg = args[1] as! String
        let peerPubkeyArg = args[2] as! String
        let forceArg = args[3] as! Bool
        do {
          try api.rlnCloseChannel(nodeId: nodeIdArg, channelId: channelIdArg, peerPubkey: peerPubkeyArg, force: forceArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      rlnCloseChannelChannel.setMessageHandler(nil)
    }
    let rlnListPaymentsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rgb_sdk_flutter.RlnHostApi.rlnListPayments\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      rlnListPaymentsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let nodeIdArg = args[0] as! Int64
        do {
          let result = try api.rlnListPayments(nodeId: nodeIdArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      rlnListPaymentsChannel.setMessageHandler(nil)
    }
    let rlnAddressChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rgb_sdk_flutter.RlnHostApi.rlnAddress\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      rlnAddressChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let nodeIdArg = args[0] as! Int64
        do {
          let result = try api.rlnAddress(nodeId: nodeIdArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      rlnAddressChannel.setMessageHandler(nil)
    }
    let rlnAssetBalanceChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rgb_sdk_flutter.RlnHostApi.rlnAssetBalance\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      rlnAssetBalanceChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let nodeIdArg = args[0] as! Int64
        let assetIdArg = args[1] as! String
        do {
          let result = try api.rlnAssetBalance(nodeId: nodeIdArg, assetId: assetIdArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      rlnAssetBalanceChannel.setMessageHandler(nil)
    }
    let rlnBackupChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rgb_sdk_flutter.RlnHostApi.rlnBackup\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      rlnBackupChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let nodeIdArg = args[0] as! Int64
        let backupPathArg = args[1] as! String
        let passwordArg = args[2] as! String
        do {
          try api.rlnBackup(nodeId: nodeIdArg, backupPath: backupPathArg, password: passwordArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      rlnBackupChannel.setMessageHandler(nil)
    }
    let rlnBtcBalanceChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rgb_sdk_flutter.RlnHostApi.rlnBtcBalance\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      rlnBtcBalanceChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let nodeIdArg = args[0] as! Int64
        let skipSyncArg = args[1] as! Bool
        do {
          let result = try api.rlnBtcBalance(nodeId: nodeIdArg, skipSync: skipSyncArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      rlnBtcBalanceChannel.setMessageHandler(nil)
    }
    let rlnCheckIndexerUrlChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rgb_sdk_flutter.RlnHostApi.rlnCheckIndexerUrl\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      rlnCheckIndexerUrlChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let nodeIdArg = args[0] as! Int64
        let indexerUrlArg = args[1] as! String
        do {
          let result = try api.rlnCheckIndexerUrl(nodeId: nodeIdArg, indexerUrl: indexerUrlArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      rlnCheckIndexerUrlChannel.setMessageHandler(nil)
    }
    let rlnCheckProxyEndpointChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rgb_sdk_flutter.RlnHostApi.rlnCheckProxyEndpoint\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      rlnCheckProxyEndpointChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let nodeIdArg = args[0] as! Int64
        let proxyEndpointArg = args[1] as! String
        do {
          try api.rlnCheckProxyEndpoint(nodeId: nodeIdArg, proxyEndpoint: proxyEndpointArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      rlnCheckProxyEndpointChannel.setMessageHandler(nil)
    }
    let rlnCreateUtxosChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rgb_sdk_flutter.RlnHostApi.rlnCreateUtxos\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      rlnCreateUtxosChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let nodeIdArg = args[0] as! Int64
        let upToArg = args[1] as! Bool
        let numArg: Int64? = nilOrValue(args[2])
        let sizeArg: Int64? = nilOrValue(args[3])
        let feeRateArg = args[4] as! Double
        let skipSyncArg = args[5] as! Bool
        do {
          try api.rlnCreateUtxos(nodeId: nodeIdArg, upTo: upToArg, num: numArg, size: sizeArg, feeRate: feeRateArg, skipSync: skipSyncArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      rlnCreateUtxosChannel.setMessageHandler(nil)
    }
    let rlnDecodeLnInvoiceChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rgb_sdk_flutter.RlnHostApi.rlnDecodeLnInvoice\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      rlnDecodeLnInvoiceChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let nodeIdArg = args[0] as! Int64
        let invoiceArg = args[1] as! String
        do {
          let result = try api.rlnDecodeLnInvoice(nodeId: nodeIdArg, invoice: invoiceArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      rlnDecodeLnInvoiceChannel.setMessageHandler(nil)
    }
    let rlnDecodeRgbInvoiceChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rgb_sdk_flutter.RlnHostApi.rlnDecodeRgbInvoice\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      rlnDecodeRgbInvoiceChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let nodeIdArg = args[0] as! Int64
        let invoiceArg = args[1] as! String
        do {
          let result = try api.rlnDecodeRgbInvoice(nodeId: nodeIdArg, invoice: invoiceArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      rlnDecodeRgbInvoiceChannel.setMessageHandler(nil)
    }
    let rlnEstimateFeeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rgb_sdk_flutter.RlnHostApi.rlnEstimateFee\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      rlnEstimateFeeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let nodeIdArg = args[0] as! Int64
        let blocksArg = args[1] as! Int64
        do {
          let result = try api.rlnEstimateFee(nodeId: nodeIdArg, blocks: blocksArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      rlnEstimateFeeChannel.setMessageHandler(nil)
    }
    let rlnFailTransfersChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rgb_sdk_flutter.RlnHostApi.rlnFailTransfers\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      rlnFailTransfersChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let nodeIdArg = args[0] as! Int64
        let batchTransferIdxArg: Int64? = nilOrValue(args[1])
        let noAssetOnlyArg = args[2] as! Bool
        let skipSyncArg = args[3] as! Bool
        do {
          let result = try api.rlnFailTransfers(nodeId: nodeIdArg, batchTransferIdx: batchTransferIdxArg, noAssetOnly: noAssetOnlyArg, skipSync: skipSyncArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      rlnFailTransfersChannel.setMessageHandler(nil)
    }
    let rlnGetChannelIdChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rgb_sdk_flutter.RlnHostApi.rlnGetChannelId\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      rlnGetChannelIdChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let nodeIdArg = args[0] as! Int64
        let temporaryChannelIdArg = args[1] as! String
        do {
          let result = try api.rlnGetChannelId(nodeId: nodeIdArg, temporaryChannelId: temporaryChannelIdArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      rlnGetChannelIdChannel.setMessageHandler(nil)
    }
    let rlnGetPaymentChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rgb_sdk_flutter.RlnHostApi.rlnGetPayment\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      rlnGetPaymentChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let nodeIdArg = args[0] as! Int64
        let paymentHashArg = args[1] as! String
        do {
          let result = try api.rlnGetPayment(nodeId: nodeIdArg, paymentHash: paymentHashArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      rlnGetPaymentChannel.setMessageHandler(nil)
    }
    let rlnInvoiceStatusChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rgb_sdk_flutter.RlnHostApi.rlnInvoiceStatus\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      rlnInvoiceStatusChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let nodeIdArg = args[0] as! Int64
        let invoiceArg = args[1] as! String
        do {
          let result = try api.rlnInvoiceStatus(nodeId: nodeIdArg, invoice: invoiceArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      rlnInvoiceStatusChannel.setMessageHandler(nil)
    }
    let rlnKeysendChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rgb_sdk_flutter.RlnHostApi.rlnKeysend\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      rlnKeysendChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let nodeIdArg = args[0] as! Int64
        let destPubkeyArg = args[1] as! String
        let amtMsatArg = args[2] as! Int64
        let assetIdArg: String? = nilOrValue(args[3])
        let assetAmountArg: Int64? = nilOrValue(args[4])
        do {
          let result = try api.rlnKeysend(nodeId: nodeIdArg, destPubkey: destPubkeyArg, amtMsat: amtMsatArg, assetId: assetIdArg, assetAmount: assetAmountArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      rlnKeysendChannel.setMessageHandler(nil)
    }
    let rlnListAssetsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rgb_sdk_flutter.RlnHostApi.rlnListAssets\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      rlnListAssetsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let nodeIdArg = args[0] as! Int64
        let filterAssetSchemasArg = args[1] as! [String]
        do {
          let result = try api.rlnListAssets(nodeId: nodeIdArg, filterAssetSchemas: filterAssetSchemasArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      rlnListAssetsChannel.setMessageHandler(nil)
    }
    let rlnListTransactionsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rgb_sdk_flutter.RlnHostApi.rlnListTransactions\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      rlnListTransactionsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let nodeIdArg = args[0] as! Int64
        let skipSyncArg = args[1] as! Bool
        do {
          let result = try api.rlnListTransactions(nodeId: nodeIdArg, skipSync: skipSyncArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      rlnListTransactionsChannel.setMessageHandler(nil)
    }
    let rlnListTransfersChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rgb_sdk_flutter.RlnHostApi.rlnListTransfers\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      rlnListTransfersChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let nodeIdArg = args[0] as! Int64
        let assetIdArg = args[1] as! String
        do {
          let result = try api.rlnListTransfers(nodeId: nodeIdArg, assetId: assetIdArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      rlnListTransfersChannel.setMessageHandler(nil)
    }
    let rlnListUnspentsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rgb_sdk_flutter.RlnHostApi.rlnListUnspents\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      rlnListUnspentsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let nodeIdArg = args[0] as! Int64
        let skipSyncArg = args[1] as! Bool
        do {
          let result = try api.rlnListUnspents(nodeId: nodeIdArg, skipSync: skipSyncArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      rlnListUnspentsChannel.setMessageHandler(nil)
    }
    let rlnLnInvoiceChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rgb_sdk_flutter.RlnHostApi.rlnLnInvoice\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      rlnLnInvoiceChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let nodeIdArg = args[0] as! Int64
        let amtMsatArg: Int64? = nilOrValue(args[1])
        let expirySecArg = args[2] as! Int64
        let assetIdArg: String? = nilOrValue(args[3])
        let assetAmountArg: Int64? = nilOrValue(args[4])
        let paymentHashArg: String? = nilOrValue(args[5])
        let minFinalCltvExpiryDeltaArg: Int64? = nilOrValue(args[6])
        do {
          let result = try api.rlnLnInvoice(nodeId: nodeIdArg, amtMsat: amtMsatArg, expirySec: expirySecArg, assetId: assetIdArg, assetAmount: assetAmountArg, paymentHash: paymentHashArg, minFinalCltvExpiryDelta: minFinalCltvExpiryDeltaArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      rlnLnInvoiceChannel.setMessageHandler(nil)
    }
    let rlnClaimHodlInvoiceChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rgb_sdk_flutter.RlnHostApi.rlnClaimHodlInvoice\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      rlnClaimHodlInvoiceChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let nodeIdArg = args[0] as! Int64
        let paymentHashArg = args[1] as! String
        let paymentPreimageArg = args[2] as! String
        do {
          let result = try api.rlnClaimHodlInvoice(nodeId: nodeIdArg, paymentHash: paymentHashArg, paymentPreimage: paymentPreimageArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      rlnClaimHodlInvoiceChannel.setMessageHandler(nil)
    }
    let rlnCancelHodlInvoiceChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rgb_sdk_flutter.RlnHostApi.rlnCancelHodlInvoice\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      rlnCancelHodlInvoiceChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let nodeIdArg = args[0] as! Int64
        let paymentHashArg = args[1] as! String
        do {
          try api.rlnCancelHodlInvoice(nodeId: nodeIdArg, paymentHash: paymentHashArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      rlnCancelHodlInvoiceChannel.setMessageHandler(nil)
    }
    let rlnApayNewChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rgb_sdk_flutter.RlnHostApi.rlnApayNew\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      rlnApayNewChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let nodeIdArg = args[0] as! Int64
        let hostNodeIdArg = args[1] as! String
        do {
          let result = try api.rlnApayNew(nodeId: nodeIdArg, hostNodeId: hostNodeIdArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      rlnApayNewChannel.setMessageHandler(nil)
    }
    let rlnApayNewWithAddressChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rgb_sdk_flutter.RlnHostApi.rlnApayNewWithAddress\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      rlnApayNewWithAddressChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let nodeIdArg = args[0] as! Int64
        let hostNodeIdArg = args[1] as! String
        let usernameArg = args[2] as! String
        let domainArg = args[3] as! String
        do {
          let result = try api.rlnApayNewWithAddress(nodeId: nodeIdArg, hostNodeId: hostNodeIdArg, username: usernameArg, domain: domainArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      rlnApayNewWithAddressChannel.setMessageHandler(nil)
    }
    let rlnRefreshTransfersChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rgb_sdk_flutter.RlnHostApi.rlnRefreshTransfers\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      rlnRefreshTransfersChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let nodeIdArg = args[0] as! Int64
        let skipSyncArg = args[1] as! Bool
        do {
          try api.rlnRefreshTransfers(nodeId: nodeIdArg, skipSync: skipSyncArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      rlnRefreshTransfersChannel.setMessageHandler(nil)
    }
    let rlnRgbInvoiceChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rgb_sdk_flutter.RlnHostApi.rlnRgbInvoice\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      rlnRgbInvoiceChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let nodeIdArg = args[0] as! Int64
        let assetIdArg: String? = nilOrValue(args[1])
        let assignmentAmountArg: Int64? = nilOrValue(args[2])
        let durationSecondsArg: Int64? = nilOrValue(args[3])
        let minConfirmationsArg = args[4] as! Int64
        let witnessArg = args[5] as! Bool
        do {
          let result = try api.rlnRgbInvoice(nodeId: nodeIdArg, assetId: assetIdArg, assignmentAmount: assignmentAmountArg, durationSeconds: durationSecondsArg, minConfirmations: minConfirmationsArg, witness: witnessArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      rlnRgbInvoiceChannel.setMessageHandler(nil)
    }
    let rlnSendBtcChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rgb_sdk_flutter.RlnHostApi.rlnSendBtc\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      rlnSendBtcChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let nodeIdArg = args[0] as! Int64
        let amountArg = args[1] as! Int64
        let addressArg = args[2] as! String
        let feeRateArg = args[3] as! Double
        let skipSyncArg = args[4] as! Bool
        do {
          let result = try api.rlnSendBtc(nodeId: nodeIdArg, amount: amountArg, address: addressArg, feeRate: feeRateArg, skipSync: skipSyncArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      rlnSendBtcChannel.setMessageHandler(nil)
    }
    let rlnSendPaymentChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rgb_sdk_flutter.RlnHostApi.rlnSendPayment\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      rlnSendPaymentChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let nodeIdArg = args[0] as! Int64
        let invoiceArg = args[1] as! String
        let amtMsatArg: Int64? = nilOrValue(args[2])
        let assetIdArg: String? = nilOrValue(args[3])
        let assetAmountArg: Int64? = nilOrValue(args[4])
        do {
          let result = try api.rlnSendPayment(nodeId: nodeIdArg, invoice: invoiceArg, amtMsat: amtMsatArg, assetId: assetIdArg, assetAmount: assetAmountArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      rlnSendPaymentChannel.setMessageHandler(nil)
    }
    let rlnSendRgbChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rgb_sdk_flutter.RlnHostApi.rlnSendRgb\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      rlnSendRgbChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let nodeIdArg = args[0] as! Int64
        let donationArg = args[1] as! Bool
        let feeRateArg = args[2] as! Double
        let minConfirmationsArg = args[3] as! Int64
        let skipSyncArg = args[4] as! Bool
        let assetIdArg = args[5] as! String
        let recipientIdArg = args[6] as! String
        let amountArg = args[7] as! Int64
        let transportEndpointsArg = args[8] as! [String]
        let witnessAmountSatArg: Int64? = nilOrValue(args[9])
        let witnessBlindingArg: Int64? = nilOrValue(args[10])
        do {
          let result = try api.rlnSendRgb(nodeId: nodeIdArg, donation: donationArg, feeRate: feeRateArg, minConfirmations: minConfirmationsArg, skipSync: skipSyncArg, assetId: assetIdArg, recipientId: recipientIdArg, amount: amountArg, transportEndpoints: transportEndpointsArg, witnessAmountSat: witnessAmountSatArg, witnessBlinding: witnessBlindingArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      rlnSendRgbChannel.setMessageHandler(nil)
    }
    let rlnShutdownChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rgb_sdk_flutter.RlnHostApi.rlnShutdown\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      rlnShutdownChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let nodeIdArg = args[0] as! Int64
        do {
          try api.rlnShutdown(nodeId: nodeIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      rlnShutdownChannel.setMessageHandler(nil)
    }
    let rlnSyncChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rgb_sdk_flutter.RlnHostApi.rlnSync\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      rlnSyncChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let nodeIdArg = args[0] as! Int64
        do {
          try api.rlnSync(nodeId: nodeIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      rlnSyncChannel.setMessageHandler(nil)
    }
    let rlnIssueAssetNiaChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rgb_sdk_flutter.RlnHostApi.rlnIssueAssetNia\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      rlnIssueAssetNiaChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let nodeIdArg = args[0] as! Int64
        let tickerArg = args[1] as! String
        let nameArg = args[2] as! String
        let precisionArg = args[3] as! Int64
        let amountsArg = args[4] as! [Int64]
        do {
          let result = try api.rlnIssueAssetNia(nodeId: nodeIdArg, ticker: tickerArg, name: nameArg, precision: precisionArg, amounts: amountsArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      rlnIssueAssetNiaChannel.setMessageHandler(nil)
    }
    let rlnIssueAssetCfaChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rgb_sdk_flutter.RlnHostApi.rlnIssueAssetCfa\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      rlnIssueAssetCfaChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let nodeIdArg = args[0] as! Int64
        let nameArg = args[1] as! String
        let detailsArg: String? = nilOrValue(args[2])
        let precisionArg = args[3] as! Int64
        let amountsArg = args[4] as! [Int64]
        let fileDigestArg: String? = nilOrValue(args[5])
        do {
          let result = try api.rlnIssueAssetCfa(nodeId: nodeIdArg, name: nameArg, details: detailsArg, precision: precisionArg, amounts: amountsArg, fileDigest: fileDigestArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      rlnIssueAssetCfaChannel.setMessageHandler(nil)
    }
    let rlnIssueAssetIfaChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rgb_sdk_flutter.RlnHostApi.rlnIssueAssetIfa\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      rlnIssueAssetIfaChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let nodeIdArg = args[0] as! Int64
        let tickerArg = args[1] as! String
        let nameArg = args[2] as! String
        let precisionArg = args[3] as! Int64
        let amountsArg = args[4] as! [Int64]
        let inflationAmountsArg = args[5] as! [Int64]
        let rejectListUrlArg: String? = nilOrValue(args[6])
        do {
          let result = try api.rlnIssueAssetIfa(nodeId: nodeIdArg, ticker: tickerArg, name: nameArg, precision: precisionArg, amounts: amountsArg, inflationAmounts: inflationAmountsArg, rejectListUrl: rejectListUrlArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      rlnIssueAssetIfaChannel.setMessageHandler(nil)
    }
    let rlnIssueAssetUdaChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rgb_sdk_flutter.RlnHostApi.rlnIssueAssetUda\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      rlnIssueAssetUdaChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let nodeIdArg = args[0] as! Int64
        let tickerArg = args[1] as! String
        let nameArg = args[2] as! String
        let detailsArg: String? = nilOrValue(args[3])
        let precisionArg = args[4] as! Int64
        let mediaFileDigestArg: String? = nilOrValue(args[5])
        let attachmentsFileDigestsArg = args[6] as! [String]
        do {
          let result = try api.rlnIssueAssetUda(nodeId: nodeIdArg, ticker: tickerArg, name: nameArg, details: detailsArg, precision: precisionArg, mediaFileDigest: mediaFileDigestArg, attachmentsFileDigests: attachmentsFileDigestsArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      rlnIssueAssetUdaChannel.setMessageHandler(nil)
    }
    let rlnVssClearFenceChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rgb_sdk_flutter.RlnHostApi.rlnVssClearFence\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      rlnVssClearFenceChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let nodeIdArg = args[0] as! Int64
        let passwordArg = args[1] as! String
        do {
          try api.rlnVssClearFence(nodeId: nodeIdArg, password: passwordArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      rlnVssClearFenceChannel.setMessageHandler(nil)
    }
  }
}
