// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.utexo.rgb_sdk_flutter

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object RlnApiPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/** Generated class from Pigeon that represents data sent in messages. */
data class RlnNativeArtifactInfo (
  val platform: String,
  val rlnVersion: String,
  val reactNativeParityVersion: String,
  val bridge: String,
  val nativeArtifact: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): RlnNativeArtifactInfo {
      val platform = pigeonVar_list[0] as String
      val rlnVersion = pigeonVar_list[1] as String
      val reactNativeParityVersion = pigeonVar_list[2] as String
      val bridge = pigeonVar_list[3] as String
      val nativeArtifact = pigeonVar_list[4] as String
      return RlnNativeArtifactInfo(platform, rlnVersion, reactNativeParityVersion, bridge, nativeArtifact)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      platform,
      rlnVersion,
      reactNativeParityVersion,
      bridge,
      nativeArtifact,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as RlnNativeArtifactInfo
    return RlnApiPigeonUtils.deepEquals(this.platform, other.platform) && RlnApiPigeonUtils.deepEquals(this.rlnVersion, other.rlnVersion) && RlnApiPigeonUtils.deepEquals(this.reactNativeParityVersion, other.reactNativeParityVersion) && RlnApiPigeonUtils.deepEquals(this.bridge, other.bridge) && RlnApiPigeonUtils.deepEquals(this.nativeArtifact, other.nativeArtifact)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + RlnApiPigeonUtils.deepHash(this.platform)
    result = 31 * result + RlnApiPigeonUtils.deepHash(this.rlnVersion)
    result = 31 * result + RlnApiPigeonUtils.deepHash(this.reactNativeParityVersion)
    result = 31 * result + RlnApiPigeonUtils.deepHash(this.bridge)
    result = 31 * result + RlnApiPigeonUtils.deepHash(this.nativeArtifact)
    return result
  }
}
private open class RlnApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          RlnNativeArtifactInfo.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is RlnNativeArtifactInfo -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface RlnHostApi {
  fun getNativeArtifactInfo(): RlnNativeArtifactInfo
  fun rlnCreateNode(storageDirPath: String, daemonListeningPort: Long, ldkPeerListeningPort: Long, network: String, maxMediaUploadSizeMb: Long, enableVirtualChannelsV0: Boolean?, virtualPeerPubkeys: List<String>?, vssUrl: String?, vssAllowHttp: Boolean, vssAllowEmptyRestore: Boolean, lspBaseUrl: String?, lspBearerToken: String?): Long
  fun rlnInitNode(nodeId: Long, password: String, mnemonic: String?): String
  fun rlnCreateNativeExternalSigner(seedHex: String, network: String, permissivePolicy: Boolean): Long
  fun rlnInitNodeWithNativeExternalSigner(nodeId: Long, signerId: Long)
  fun rlnAttachNativeExternalSigner(nodeId: Long, signerId: Long)
  fun rlnUnlockNodeWithNativeExternalSigner(nodeId: Long, signerId: Long, bitcoindRpcUsername: String?, bitcoindRpcPassword: String?, bitcoindRpcHost: String?, bitcoindRpcPort: Long?, indexerUrl: String?, proxyEndpoint: String?, announceAddresses: List<String>, announceAlias: String?, gossipRgsServerUrl: String?)
  fun rlnDestroyNativeExternalSigner(signerId: Long)
  fun rlnInitNodeWithExternalSigner(nodeId: Long, nodePublicKeyHex: String, accountXpubVanilla: String, accountXpubColored: String, masterFingerprint: String, protocolVersion: String, apiLevel: Long)
  fun rlnUnlockNode(nodeId: Long, password: String, bitcoindRpcUsername: String?, bitcoindRpcPassword: String?, bitcoindRpcHost: String?, bitcoindRpcPort: Long?, indexerUrl: String?, proxyEndpoint: String?, announceAddresses: List<String>, announceAlias: String?, gossipRgsServerUrl: String?)
  fun rlnDestroyNode(nodeId: Long)
  fun rlnNodeInfo(nodeId: Long): Map<Any?, Any?>
  fun rlnNetworkInfo(nodeId: Long): Map<Any?, Any?>
  fun rlnListPeers(nodeId: Long): List<Map<Any?, Any?>>
  fun rlnConnectPeer(nodeId: Long, peerPubkeyAndAddr: String)
  fun rlnDisconnectPeer(nodeId: Long, peerPubkey: String)
  fun rlnListChannels(nodeId: Long): List<Map<Any?, Any?>>
  fun rlnOpenChannel(nodeId: Long, peerPubkeyAndOptAddr: String, capacitySat: Long, pushMsat: Long, publicChannel: Boolean, withAnchors: Boolean, feeBaseMsat: Long?, feeProportionalMillionths: Long?, temporaryChannelId: String?, assetId: String?, assetAmount: Long?, pushAssetAmount: Long?, virtualOpenMode: String?): Map<Any?, Any?>
  fun rlnCloseChannel(nodeId: Long, channelId: String, peerPubkey: String, force: Boolean)
  fun rlnListPayments(nodeId: Long): List<Map<Any?, Any?>>
  fun rlnAddress(nodeId: Long): Map<Any?, Any?>
  fun rlnAssetBalance(nodeId: Long, assetId: String): Map<Any?, Any?>
  fun rlnBackup(nodeId: Long, backupPath: String, password: String)
  fun rlnBtcBalance(nodeId: Long, skipSync: Boolean): Map<Any?, Any?>
  fun rlnCheckIndexerUrl(nodeId: Long, indexerUrl: String): Map<Any?, Any?>
  fun rlnCheckProxyEndpoint(nodeId: Long, proxyEndpoint: String)
  fun rlnCreateUtxos(nodeId: Long, upTo: Boolean, num: Long?, size: Long?, feeRate: Double, skipSync: Boolean)
  fun rlnDecodeLnInvoice(nodeId: Long, invoice: String): Map<Any?, Any?>
  fun rlnDecodeRgbInvoice(nodeId: Long, invoice: String): Map<Any?, Any?>
  fun rlnEstimateFee(nodeId: Long, blocks: Long): Map<Any?, Any?>
  fun rlnFailTransfers(nodeId: Long, batchTransferIdx: Long?, noAssetOnly: Boolean, skipSync: Boolean): Map<Any?, Any?>
  fun rlnGetChannelId(nodeId: Long, temporaryChannelId: String): String
  fun rlnGetPayment(nodeId: Long, paymentHash: String): Map<Any?, Any?>
  fun rlnInvoiceStatus(nodeId: Long, invoice: String): Map<Any?, Any?>
  fun rlnKeysend(nodeId: Long, destPubkey: String, amtMsat: Long, assetId: String?, assetAmount: Long?): Map<Any?, Any?>
  fun rlnListAssets(nodeId: Long, filterAssetSchemas: List<String>): Map<Any?, Any?>
  fun rlnListTransactions(nodeId: Long, skipSync: Boolean): List<Map<Any?, Any?>>
  fun rlnListTransfers(nodeId: Long, assetId: String): List<Map<Any?, Any?>>
  fun rlnListUnspents(nodeId: Long, skipSync: Boolean): List<Map<Any?, Any?>>
  fun rlnLnInvoice(nodeId: Long, amtMsat: Long?, expirySec: Long, assetId: String?, assetAmount: Long?, paymentHash: String?, minFinalCltvExpiryDelta: Long?): Map<Any?, Any?>
  fun rlnClaimHodlInvoice(nodeId: Long, paymentHash: String, paymentPreimage: String): Map<Any?, Any?>
  fun rlnCancelHodlInvoice(nodeId: Long, paymentHash: String)
  fun rlnApayNew(nodeId: Long, hostNodeId: String): Map<Any?, Any?>
  fun rlnApayNewWithAddress(nodeId: Long, hostNodeId: String, username: String, domain: String): Map<Any?, Any?>
  fun rlnRefreshTransfers(nodeId: Long, skipSync: Boolean)
  fun rlnRgbInvoice(nodeId: Long, assetId: String?, assignmentAmount: Long?, durationSeconds: Long?, minConfirmations: Long, witness: Boolean): Map<Any?, Any?>
  fun rlnSendBtc(nodeId: Long, amount: Long, address: String, feeRate: Double, skipSync: Boolean): Map<Any?, Any?>
  fun rlnSendPayment(nodeId: Long, invoice: String, amtMsat: Long?, assetId: String?, assetAmount: Long?): Map<Any?, Any?>
  fun rlnSendRgb(nodeId: Long, donation: Boolean, feeRate: Double, minConfirmations: Long, skipSync: Boolean, assetId: String, recipientId: String, amount: Long, transportEndpoints: List<String>, witnessAmountSat: Long?, witnessBlinding: Long?): Map<Any?, Any?>
  fun rlnShutdown(nodeId: Long)
  fun rlnSync(nodeId: Long)
  fun rlnIssueAssetNia(nodeId: Long, ticker: String, name: String, precision: Long, amounts: List<Long>): Any?
  fun rlnIssueAssetCfa(nodeId: Long, name: String, details: String?, precision: Long, amounts: List<Long>, fileDigest: String?): Any?
  fun rlnIssueAssetIfa(nodeId: Long, ticker: String, name: String, precision: Long, amounts: List<Long>, inflationAmounts: List<Long>, rejectListUrl: String?): Any?
  fun rlnIssueAssetUda(nodeId: Long, ticker: String, name: String, details: String?, precision: Long, mediaFileDigest: String?, attachmentsFileDigests: List<String>): Any?
  fun rlnVssClearFence(nodeId: Long, password: String)

  companion object {
    /** The codec used by RlnHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      RlnApiPigeonCodec()
    }
    /** Sets up an instance of `RlnHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: RlnHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rgb_sdk_flutter.RlnHostApi.getNativeArtifactInfo$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getNativeArtifactInfo())
            } catch (exception: Throwable) {
              RlnApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rgb_sdk_flutter.RlnHostApi.rlnCreateNode$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val storageDirPathArg = args[0] as String
            val daemonListeningPortArg = args[1] as Long
            val ldkPeerListeningPortArg = args[2] as Long
            val networkArg = args[3] as String
            val maxMediaUploadSizeMbArg = args[4] as Long
            val enableVirtualChannelsV0Arg = args[5] as Boolean?
            val virtualPeerPubkeysArg = args[6] as List<String>?
            val vssUrlArg = args[7] as String?
            val vssAllowHttpArg = args[8] as Boolean
            val vssAllowEmptyRestoreArg = args[9] as Boolean
            val lspBaseUrlArg = args[10] as String?
            val lspBearerTokenArg = args[11] as String?
            val wrapped: List<Any?> = try {
              listOf(api.rlnCreateNode(storageDirPathArg, daemonListeningPortArg, ldkPeerListeningPortArg, networkArg, maxMediaUploadSizeMbArg, enableVirtualChannelsV0Arg, virtualPeerPubkeysArg, vssUrlArg, vssAllowHttpArg, vssAllowEmptyRestoreArg, lspBaseUrlArg, lspBearerTokenArg))
            } catch (exception: Throwable) {
              RlnApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rgb_sdk_flutter.RlnHostApi.rlnInitNode$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val nodeIdArg = args[0] as Long
            val passwordArg = args[1] as String
            val mnemonicArg = args[2] as String?
            val wrapped: List<Any?> = try {
              listOf(api.rlnInitNode(nodeIdArg, passwordArg, mnemonicArg))
            } catch (exception: Throwable) {
              RlnApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rgb_sdk_flutter.RlnHostApi.rlnCreateNativeExternalSigner$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val seedHexArg = args[0] as String
            val networkArg = args[1] as String
            val permissivePolicyArg = args[2] as Boolean
            val wrapped: List<Any?> = try {
              listOf(api.rlnCreateNativeExternalSigner(seedHexArg, networkArg, permissivePolicyArg))
            } catch (exception: Throwable) {
              RlnApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rgb_sdk_flutter.RlnHostApi.rlnInitNodeWithNativeExternalSigner$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val nodeIdArg = args[0] as Long
            val signerIdArg = args[1] as Long
            val wrapped: List<Any?> = try {
              api.rlnInitNodeWithNativeExternalSigner(nodeIdArg, signerIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              RlnApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rgb_sdk_flutter.RlnHostApi.rlnAttachNativeExternalSigner$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val nodeIdArg = args[0] as Long
            val signerIdArg = args[1] as Long
            val wrapped: List<Any?> = try {
              api.rlnAttachNativeExternalSigner(nodeIdArg, signerIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              RlnApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rgb_sdk_flutter.RlnHostApi.rlnUnlockNodeWithNativeExternalSigner$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val nodeIdArg = args[0] as Long
            val signerIdArg = args[1] as Long
            val bitcoindRpcUsernameArg = args[2] as String?
            val bitcoindRpcPasswordArg = args[3] as String?
            val bitcoindRpcHostArg = args[4] as String?
            val bitcoindRpcPortArg = args[5] as Long?
            val indexerUrlArg = args[6] as String?
            val proxyEndpointArg = args[7] as String?
            val announceAddressesArg = args[8] as List<String>
            val announceAliasArg = args[9] as String?
            val gossipRgsServerUrlArg = args[10] as String?
            val wrapped: List<Any?> = try {
              api.rlnUnlockNodeWithNativeExternalSigner(nodeIdArg, signerIdArg, bitcoindRpcUsernameArg, bitcoindRpcPasswordArg, bitcoindRpcHostArg, bitcoindRpcPortArg, indexerUrlArg, proxyEndpointArg, announceAddressesArg, announceAliasArg, gossipRgsServerUrlArg)
              listOf(null)
            } catch (exception: Throwable) {
              RlnApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rgb_sdk_flutter.RlnHostApi.rlnDestroyNativeExternalSigner$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val signerIdArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.rlnDestroyNativeExternalSigner(signerIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              RlnApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rgb_sdk_flutter.RlnHostApi.rlnInitNodeWithExternalSigner$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val nodeIdArg = args[0] as Long
            val nodePublicKeyHexArg = args[1] as String
            val accountXpubVanillaArg = args[2] as String
            val accountXpubColoredArg = args[3] as String
            val masterFingerprintArg = args[4] as String
            val protocolVersionArg = args[5] as String
            val apiLevelArg = args[6] as Long
            val wrapped: List<Any?> = try {
              api.rlnInitNodeWithExternalSigner(nodeIdArg, nodePublicKeyHexArg, accountXpubVanillaArg, accountXpubColoredArg, masterFingerprintArg, protocolVersionArg, apiLevelArg)
              listOf(null)
            } catch (exception: Throwable) {
              RlnApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rgb_sdk_flutter.RlnHostApi.rlnUnlockNode$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val nodeIdArg = args[0] as Long
            val passwordArg = args[1] as String
            val bitcoindRpcUsernameArg = args[2] as String?
            val bitcoindRpcPasswordArg = args[3] as String?
            val bitcoindRpcHostArg = args[4] as String?
            val bitcoindRpcPortArg = args[5] as Long?
            val indexerUrlArg = args[6] as String?
            val proxyEndpointArg = args[7] as String?
            val announceAddressesArg = args[8] as List<String>
            val announceAliasArg = args[9] as String?
            val gossipRgsServerUrlArg = args[10] as String?
            val wrapped: List<Any?> = try {
              api.rlnUnlockNode(nodeIdArg, passwordArg, bitcoindRpcUsernameArg, bitcoindRpcPasswordArg, bitcoindRpcHostArg, bitcoindRpcPortArg, indexerUrlArg, proxyEndpointArg, announceAddressesArg, announceAliasArg, gossipRgsServerUrlArg)
              listOf(null)
            } catch (exception: Throwable) {
              RlnApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rgb_sdk_flutter.RlnHostApi.rlnDestroyNode$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val nodeIdArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.rlnDestroyNode(nodeIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              RlnApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rgb_sdk_flutter.RlnHostApi.rlnNodeInfo$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val nodeIdArg = args[0] as Long
            val wrapped: List<Any?> = try {
              listOf(api.rlnNodeInfo(nodeIdArg))
            } catch (exception: Throwable) {
              RlnApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rgb_sdk_flutter.RlnHostApi.rlnNetworkInfo$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val nodeIdArg = args[0] as Long
            val wrapped: List<Any?> = try {
              listOf(api.rlnNetworkInfo(nodeIdArg))
            } catch (exception: Throwable) {
              RlnApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rgb_sdk_flutter.RlnHostApi.rlnListPeers$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val nodeIdArg = args[0] as Long
            val wrapped: List<Any?> = try {
              listOf(api.rlnListPeers(nodeIdArg))
            } catch (exception: Throwable) {
              RlnApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rgb_sdk_flutter.RlnHostApi.rlnConnectPeer$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val nodeIdArg = args[0] as Long
            val peerPubkeyAndAddrArg = args[1] as String
            val wrapped: List<Any?> = try {
              api.rlnConnectPeer(nodeIdArg, peerPubkeyAndAddrArg)
              listOf(null)
            } catch (exception: Throwable) {
              RlnApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rgb_sdk_flutter.RlnHostApi.rlnDisconnectPeer$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val nodeIdArg = args[0] as Long
            val peerPubkeyArg = args[1] as String
            val wrapped: List<Any?> = try {
              api.rlnDisconnectPeer(nodeIdArg, peerPubkeyArg)
              listOf(null)
            } catch (exception: Throwable) {
              RlnApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rgb_sdk_flutter.RlnHostApi.rlnListChannels$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val nodeIdArg = args[0] as Long
            val wrapped: List<Any?> = try {
              listOf(api.rlnListChannels(nodeIdArg))
            } catch (exception: Throwable) {
              RlnApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rgb_sdk_flutter.RlnHostApi.rlnOpenChannel$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val nodeIdArg = args[0] as Long
            val peerPubkeyAndOptAddrArg = args[1] as String
            val capacitySatArg = args[2] as Long
            val pushMsatArg = args[3] as Long
            val publicChannelArg = args[4] as Boolean
            val withAnchorsArg = args[5] as Boolean
            val feeBaseMsatArg = args[6] as Long?
            val feeProportionalMillionthsArg = args[7] as Long?
            val temporaryChannelIdArg = args[8] as String?
            val assetIdArg = args[9] as String?
            val assetAmountArg = args[10] as Long?
            val pushAssetAmountArg = args[11] as Long?
            val virtualOpenModeArg = args[12] as String?
            val wrapped: List<Any?> = try {
              listOf(api.rlnOpenChannel(nodeIdArg, peerPubkeyAndOptAddrArg, capacitySatArg, pushMsatArg, publicChannelArg, withAnchorsArg, feeBaseMsatArg, feeProportionalMillionthsArg, temporaryChannelIdArg, assetIdArg, assetAmountArg, pushAssetAmountArg, virtualOpenModeArg))
            } catch (exception: Throwable) {
              RlnApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rgb_sdk_flutter.RlnHostApi.rlnCloseChannel$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val nodeIdArg = args[0] as Long
            val channelIdArg = args[1] as String
            val peerPubkeyArg = args[2] as String
            val forceArg = args[3] as Boolean
            val wrapped: List<Any?> = try {
              api.rlnCloseChannel(nodeIdArg, channelIdArg, peerPubkeyArg, forceArg)
              listOf(null)
            } catch (exception: Throwable) {
              RlnApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rgb_sdk_flutter.RlnHostApi.rlnListPayments$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val nodeIdArg = args[0] as Long
            val wrapped: List<Any?> = try {
              listOf(api.rlnListPayments(nodeIdArg))
            } catch (exception: Throwable) {
              RlnApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rgb_sdk_flutter.RlnHostApi.rlnAddress$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val nodeIdArg = args[0] as Long
            val wrapped: List<Any?> = try {
              listOf(api.rlnAddress(nodeIdArg))
            } catch (exception: Throwable) {
              RlnApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rgb_sdk_flutter.RlnHostApi.rlnAssetBalance$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val nodeIdArg = args[0] as Long
            val assetIdArg = args[1] as String
            val wrapped: List<Any?> = try {
              listOf(api.rlnAssetBalance(nodeIdArg, assetIdArg))
            } catch (exception: Throwable) {
              RlnApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rgb_sdk_flutter.RlnHostApi.rlnBackup$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val nodeIdArg = args[0] as Long
            val backupPathArg = args[1] as String
            val passwordArg = args[2] as String
            val wrapped: List<Any?> = try {
              api.rlnBackup(nodeIdArg, backupPathArg, passwordArg)
              listOf(null)
            } catch (exception: Throwable) {
              RlnApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rgb_sdk_flutter.RlnHostApi.rlnBtcBalance$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val nodeIdArg = args[0] as Long
            val skipSyncArg = args[1] as Boolean
            val wrapped: List<Any?> = try {
              listOf(api.rlnBtcBalance(nodeIdArg, skipSyncArg))
            } catch (exception: Throwable) {
              RlnApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rgb_sdk_flutter.RlnHostApi.rlnCheckIndexerUrl$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val nodeIdArg = args[0] as Long
            val indexerUrlArg = args[1] as String
            val wrapped: List<Any?> = try {
              listOf(api.rlnCheckIndexerUrl(nodeIdArg, indexerUrlArg))
            } catch (exception: Throwable) {
              RlnApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rgb_sdk_flutter.RlnHostApi.rlnCheckProxyEndpoint$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val nodeIdArg = args[0] as Long
            val proxyEndpointArg = args[1] as String
            val wrapped: List<Any?> = try {
              api.rlnCheckProxyEndpoint(nodeIdArg, proxyEndpointArg)
              listOf(null)
            } catch (exception: Throwable) {
              RlnApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rgb_sdk_flutter.RlnHostApi.rlnCreateUtxos$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val nodeIdArg = args[0] as Long
            val upToArg = args[1] as Boolean
            val numArg = args[2] as Long?
            val sizeArg = args[3] as Long?
            val feeRateArg = args[4] as Double
            val skipSyncArg = args[5] as Boolean
            val wrapped: List<Any?> = try {
              api.rlnCreateUtxos(nodeIdArg, upToArg, numArg, sizeArg, feeRateArg, skipSyncArg)
              listOf(null)
            } catch (exception: Throwable) {
              RlnApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rgb_sdk_flutter.RlnHostApi.rlnDecodeLnInvoice$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val nodeIdArg = args[0] as Long
            val invoiceArg = args[1] as String
            val wrapped: List<Any?> = try {
              listOf(api.rlnDecodeLnInvoice(nodeIdArg, invoiceArg))
            } catch (exception: Throwable) {
              RlnApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rgb_sdk_flutter.RlnHostApi.rlnDecodeRgbInvoice$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val nodeIdArg = args[0] as Long
            val invoiceArg = args[1] as String
            val wrapped: List<Any?> = try {
              listOf(api.rlnDecodeRgbInvoice(nodeIdArg, invoiceArg))
            } catch (exception: Throwable) {
              RlnApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rgb_sdk_flutter.RlnHostApi.rlnEstimateFee$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val nodeIdArg = args[0] as Long
            val blocksArg = args[1] as Long
            val wrapped: List<Any?> = try {
              listOf(api.rlnEstimateFee(nodeIdArg, blocksArg))
            } catch (exception: Throwable) {
              RlnApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rgb_sdk_flutter.RlnHostApi.rlnFailTransfers$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val nodeIdArg = args[0] as Long
            val batchTransferIdxArg = args[1] as Long?
            val noAssetOnlyArg = args[2] as Boolean
            val skipSyncArg = args[3] as Boolean
            val wrapped: List<Any?> = try {
              listOf(api.rlnFailTransfers(nodeIdArg, batchTransferIdxArg, noAssetOnlyArg, skipSyncArg))
            } catch (exception: Throwable) {
              RlnApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rgb_sdk_flutter.RlnHostApi.rlnGetChannelId$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val nodeIdArg = args[0] as Long
            val temporaryChannelIdArg = args[1] as String
            val wrapped: List<Any?> = try {
              listOf(api.rlnGetChannelId(nodeIdArg, temporaryChannelIdArg))
            } catch (exception: Throwable) {
              RlnApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rgb_sdk_flutter.RlnHostApi.rlnGetPayment$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val nodeIdArg = args[0] as Long
            val paymentHashArg = args[1] as String
            val wrapped: List<Any?> = try {
              listOf(api.rlnGetPayment(nodeIdArg, paymentHashArg))
            } catch (exception: Throwable) {
              RlnApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rgb_sdk_flutter.RlnHostApi.rlnInvoiceStatus$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val nodeIdArg = args[0] as Long
            val invoiceArg = args[1] as String
            val wrapped: List<Any?> = try {
              listOf(api.rlnInvoiceStatus(nodeIdArg, invoiceArg))
            } catch (exception: Throwable) {
              RlnApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rgb_sdk_flutter.RlnHostApi.rlnKeysend$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val nodeIdArg = args[0] as Long
            val destPubkeyArg = args[1] as String
            val amtMsatArg = args[2] as Long
            val assetIdArg = args[3] as String?
            val assetAmountArg = args[4] as Long?
            val wrapped: List<Any?> = try {
              listOf(api.rlnKeysend(nodeIdArg, destPubkeyArg, amtMsatArg, assetIdArg, assetAmountArg))
            } catch (exception: Throwable) {
              RlnApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rgb_sdk_flutter.RlnHostApi.rlnListAssets$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val nodeIdArg = args[0] as Long
            val filterAssetSchemasArg = args[1] as List<String>
            val wrapped: List<Any?> = try {
              listOf(api.rlnListAssets(nodeIdArg, filterAssetSchemasArg))
            } catch (exception: Throwable) {
              RlnApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rgb_sdk_flutter.RlnHostApi.rlnListTransactions$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val nodeIdArg = args[0] as Long
            val skipSyncArg = args[1] as Boolean
            val wrapped: List<Any?> = try {
              listOf(api.rlnListTransactions(nodeIdArg, skipSyncArg))
            } catch (exception: Throwable) {
              RlnApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rgb_sdk_flutter.RlnHostApi.rlnListTransfers$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val nodeIdArg = args[0] as Long
            val assetIdArg = args[1] as String
            val wrapped: List<Any?> = try {
              listOf(api.rlnListTransfers(nodeIdArg, assetIdArg))
            } catch (exception: Throwable) {
              RlnApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rgb_sdk_flutter.RlnHostApi.rlnListUnspents$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val nodeIdArg = args[0] as Long
            val skipSyncArg = args[1] as Boolean
            val wrapped: List<Any?> = try {
              listOf(api.rlnListUnspents(nodeIdArg, skipSyncArg))
            } catch (exception: Throwable) {
              RlnApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rgb_sdk_flutter.RlnHostApi.rlnLnInvoice$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val nodeIdArg = args[0] as Long
            val amtMsatArg = args[1] as Long?
            val expirySecArg = args[2] as Long
            val assetIdArg = args[3] as String?
            val assetAmountArg = args[4] as Long?
            val paymentHashArg = args[5] as String?
            val minFinalCltvExpiryDeltaArg = args[6] as Long?
            val wrapped: List<Any?> = try {
              listOf(api.rlnLnInvoice(nodeIdArg, amtMsatArg, expirySecArg, assetIdArg, assetAmountArg, paymentHashArg, minFinalCltvExpiryDeltaArg))
            } catch (exception: Throwable) {
              RlnApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rgb_sdk_flutter.RlnHostApi.rlnClaimHodlInvoice$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val nodeIdArg = args[0] as Long
            val paymentHashArg = args[1] as String
            val paymentPreimageArg = args[2] as String
            val wrapped: List<Any?> = try {
              listOf(api.rlnClaimHodlInvoice(nodeIdArg, paymentHashArg, paymentPreimageArg))
            } catch (exception: Throwable) {
              RlnApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rgb_sdk_flutter.RlnHostApi.rlnCancelHodlInvoice$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val nodeIdArg = args[0] as Long
            val paymentHashArg = args[1] as String
            val wrapped: List<Any?> = try {
              api.rlnCancelHodlInvoice(nodeIdArg, paymentHashArg)
              listOf(null)
            } catch (exception: Throwable) {
              RlnApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rgb_sdk_flutter.RlnHostApi.rlnApayNew$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val nodeIdArg = args[0] as Long
            val hostNodeIdArg = args[1] as String
            val wrapped: List<Any?> = try {
              listOf(api.rlnApayNew(nodeIdArg, hostNodeIdArg))
            } catch (exception: Throwable) {
              RlnApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rgb_sdk_flutter.RlnHostApi.rlnApayNewWithAddress$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val nodeIdArg = args[0] as Long
            val hostNodeIdArg = args[1] as String
            val usernameArg = args[2] as String
            val domainArg = args[3] as String
            val wrapped: List<Any?> = try {
              listOf(api.rlnApayNewWithAddress(nodeIdArg, hostNodeIdArg, usernameArg, domainArg))
            } catch (exception: Throwable) {
              RlnApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rgb_sdk_flutter.RlnHostApi.rlnRefreshTransfers$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val nodeIdArg = args[0] as Long
            val skipSyncArg = args[1] as Boolean
            val wrapped: List<Any?> = try {
              api.rlnRefreshTransfers(nodeIdArg, skipSyncArg)
              listOf(null)
            } catch (exception: Throwable) {
              RlnApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rgb_sdk_flutter.RlnHostApi.rlnRgbInvoice$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val nodeIdArg = args[0] as Long
            val assetIdArg = args[1] as String?
            val assignmentAmountArg = args[2] as Long?
            val durationSecondsArg = args[3] as Long?
            val minConfirmationsArg = args[4] as Long
            val witnessArg = args[5] as Boolean
            val wrapped: List<Any?> = try {
              listOf(api.rlnRgbInvoice(nodeIdArg, assetIdArg, assignmentAmountArg, durationSecondsArg, minConfirmationsArg, witnessArg))
            } catch (exception: Throwable) {
              RlnApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rgb_sdk_flutter.RlnHostApi.rlnSendBtc$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val nodeIdArg = args[0] as Long
            val amountArg = args[1] as Long
            val addressArg = args[2] as String
            val feeRateArg = args[3] as Double
            val skipSyncArg = args[4] as Boolean
            val wrapped: List<Any?> = try {
              listOf(api.rlnSendBtc(nodeIdArg, amountArg, addressArg, feeRateArg, skipSyncArg))
            } catch (exception: Throwable) {
              RlnApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rgb_sdk_flutter.RlnHostApi.rlnSendPayment$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val nodeIdArg = args[0] as Long
            val invoiceArg = args[1] as String
            val amtMsatArg = args[2] as Long?
            val assetIdArg = args[3] as String?
            val assetAmountArg = args[4] as Long?
            val wrapped: List<Any?> = try {
              listOf(api.rlnSendPayment(nodeIdArg, invoiceArg, amtMsatArg, assetIdArg, assetAmountArg))
            } catch (exception: Throwable) {
              RlnApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rgb_sdk_flutter.RlnHostApi.rlnSendRgb$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val nodeIdArg = args[0] as Long
            val donationArg = args[1] as Boolean
            val feeRateArg = args[2] as Double
            val minConfirmationsArg = args[3] as Long
            val skipSyncArg = args[4] as Boolean
            val assetIdArg = args[5] as String
            val recipientIdArg = args[6] as String
            val amountArg = args[7] as Long
            val transportEndpointsArg = args[8] as List<String>
            val witnessAmountSatArg = args[9] as Long?
            val witnessBlindingArg = args[10] as Long?
            val wrapped: List<Any?> = try {
              listOf(api.rlnSendRgb(nodeIdArg, donationArg, feeRateArg, minConfirmationsArg, skipSyncArg, assetIdArg, recipientIdArg, amountArg, transportEndpointsArg, witnessAmountSatArg, witnessBlindingArg))
            } catch (exception: Throwable) {
              RlnApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rgb_sdk_flutter.RlnHostApi.rlnShutdown$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val nodeIdArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.rlnShutdown(nodeIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              RlnApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rgb_sdk_flutter.RlnHostApi.rlnSync$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val nodeIdArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.rlnSync(nodeIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              RlnApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rgb_sdk_flutter.RlnHostApi.rlnIssueAssetNia$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val nodeIdArg = args[0] as Long
            val tickerArg = args[1] as String
            val nameArg = args[2] as String
            val precisionArg = args[3] as Long
            val amountsArg = args[4] as List<Long>
            val wrapped: List<Any?> = try {
              listOf(api.rlnIssueAssetNia(nodeIdArg, tickerArg, nameArg, precisionArg, amountsArg))
            } catch (exception: Throwable) {
              RlnApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rgb_sdk_flutter.RlnHostApi.rlnIssueAssetCfa$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val nodeIdArg = args[0] as Long
            val nameArg = args[1] as String
            val detailsArg = args[2] as String?
            val precisionArg = args[3] as Long
            val amountsArg = args[4] as List<Long>
            val fileDigestArg = args[5] as String?
            val wrapped: List<Any?> = try {
              listOf(api.rlnIssueAssetCfa(nodeIdArg, nameArg, detailsArg, precisionArg, amountsArg, fileDigestArg))
            } catch (exception: Throwable) {
              RlnApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rgb_sdk_flutter.RlnHostApi.rlnIssueAssetIfa$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val nodeIdArg = args[0] as Long
            val tickerArg = args[1] as String
            val nameArg = args[2] as String
            val precisionArg = args[3] as Long
            val amountsArg = args[4] as List<Long>
            val inflationAmountsArg = args[5] as List<Long>
            val rejectListUrlArg = args[6] as String?
            val wrapped: List<Any?> = try {
              listOf(api.rlnIssueAssetIfa(nodeIdArg, tickerArg, nameArg, precisionArg, amountsArg, inflationAmountsArg, rejectListUrlArg))
            } catch (exception: Throwable) {
              RlnApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rgb_sdk_flutter.RlnHostApi.rlnIssueAssetUda$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val nodeIdArg = args[0] as Long
            val tickerArg = args[1] as String
            val nameArg = args[2] as String
            val detailsArg = args[3] as String?
            val precisionArg = args[4] as Long
            val mediaFileDigestArg = args[5] as String?
            val attachmentsFileDigestsArg = args[6] as List<String>
            val wrapped: List<Any?> = try {
              listOf(api.rlnIssueAssetUda(nodeIdArg, tickerArg, nameArg, detailsArg, precisionArg, mediaFileDigestArg, attachmentsFileDigestsArg))
            } catch (exception: Throwable) {
              RlnApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rgb_sdk_flutter.RlnHostApi.rlnVssClearFence$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val nodeIdArg = args[0] as Long
            val passwordArg = args[1] as String
            val wrapped: List<Any?> = try {
              api.rlnVssClearFence(nodeIdArg, passwordArg)
              listOf(null)
            } catch (exception: Throwable) {
              RlnApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
