name: rgb-sdk-flutter-regtest

services:
  bitcoind:
    image: registry.gitlab.com/hashbeam/docker/bitcoind:30.0
    platform: linux/amd64
    command: "-fallbackfee=0.0002"
    environment:
      MYUID: "${MYUID:-1000}"
      MYGID: "${MYGID:-1000}"
      RPCAUTH: "user:84c66d54d736d8b02aaa5b02e07e759b$$cc56c229b2a49ae2bfd5932cc8a6135d435bb9a7ac037ddd351d65936082c03d"
    ports:
      - "${BITCOIND_RPC_PORT:-18444}:18443"
    volumes:
      - ./data/bitcoind:/srv/app/.bitcoin

  electrs:
    image: registry.gitlab.com/hashbeam/docker/electrs:0.10.10
    platform: linux/amd64
    environment:
      MYUID: "${MYUID:-1000}"
      MYGID: "${MYGID:-1000}"
      BTCPASS: "password"
    depends_on:
      - bitcoind
    ports:
      - "${ELECTRS_PORT:-50002}:50001"
    volumes:
      - ./data/electrs:/srv/app/db

  proxy:
    image: ghcr.io/rgb-tools/rgb-proxy-server:0.3.0
    platform: linux/amd64
    ports:
      - "${RGB_PROXY_PORT:-3003}:3000"
